"""Model registry — import all models so Alembic metadata is complete."""
from app.models.base import (
    Base,
    BaseModel,
    DebateMode,
    DebateStatus,
    DepositStatus,
    DisputeStatus,
    FinancialState,
    GameStatus,
    GameType,
    LedgerAccount,
    NotificationChannel,
    ParticipantRole,
    Side,
    TransactionType,
    UserRole,
    UserStatus,
    VoteChoice,
    WithdrawalStatus,
)
from app.models.category import DEFAULT_CATEGORIES, Category
from app.models.debate import (
    Debate,
    DebateEvent,
    DebateInvitation,
    DebateParticipant,
    DebateRules,
    DebateVote,
)
from app.models.notification import AuditLog, Dispute, Game, Notification
from app.models.payment import (
    Deposit,
    PaymentProvider,
    SettlementRecord,
    Withdrawal,
)
from app.models.user import Follow, Profile, User, UserPreferences, UserSession
from app.models.wallet import LedgerEntry, PaymentTransaction, Wallet, WalletAccount

__all__ = [
    "Base",
    "BaseModel",
    "User",
    "Profile",
    "UserPreferences",
    "UserSession",
    "Follow",
    "Category",
    "DEFAULT_CATEGORIES",
    "Debate",
    "DebateRules",
    "DebateParticipant",
    "DebateVote",
    "DebateInvitation",
    "DebateEvent",
    "Wallet",
    "WalletAccount",
    "PaymentTransaction",
    "LedgerEntry",
    "Deposit",
    "Withdrawal",
    "PaymentProvider",
    "SettlementRecord",
    "Notification",
    "Dispute",
    "AuditLog",
    "Game",
    # enums
    "UserRole",
    "UserStatus",
    "DebateMode",
    "DebateStatus",
    "Side",
    "ParticipantRole",
    "VoteChoice",
    "FinancialState",
    "TransactionType",
    "WithdrawalStatus",
    "DepositStatus",
    "LedgerAccount",
    "DisputeStatus",
    "NotificationChannel",
    "GameType",
    "GameStatus",
]
